// Code generated by sqlc. DO NOT EDIT.

package users

import (
	"database/sql"
)

type User struct {
	ID           int64         `json:"id"`
	Firstname    string        `json:"firstname"`
	Lastname     string        `json:"lastname"`
	Email        string        `json:"email"`
	Upassword    string        `json:"upassword"`
	Isambassador sql.NullInt32 `json:"isambassador"`
}
