// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package links

import (
	"context"
)

const getAllLinks = `-- name: GetAllLinks :many
 SELECT id, code, user_id FROM links
 ORDER BY id ASC
`

func (q *Queries) GetAllLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, getAllLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(&i.ID, &i.Code, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
