// Code generated by sqlc. DO NOT EDIT.

package database

import (
	"database/sql"
)

type User struct {
	ID           int64
	Firstname    string
	Lastname     string
	Email        string
	Upassword    string
	Isambassador sql.NullInt32
}
