// Code generated by sqlc. DO NOT EDIT.

package products

import ()

type Product struct {
	ID          int64   `json:"id"`
	Category    string  `json:"category"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Image       string  `json:"image"`
	Price       float64 `json:"price"`
}
