// Code generated by sqlc. DO NOT EDIT.

package orders

import ()

type Order struct {
	ID              int64  `json:"id"`
	TransactionID   string `json:"transaction_id"`
	UserID          int64  `json:"user_id"`
	Code            string `json:"code"`
	AmbassadorEmail string `json:"ambassador_email"`
	Firstname       string `json:"firstname"`
	Lastname        string `json:"lastname"`
	Email           string `json:"email"`
	Address         string `json:"address"`
	City            string `json:"city"`
	Country         string `json:"country"`
	Zip             string `json:"zip"`
	Complete        bool   `json:"complete"`
}
