// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package orders

import (
	"context"
)

const getAllOrders = `-- name: GetAllOrders :many
 SELECT id, transaction_id, user_id, code, ambassador_email, firstname, lastname, email, address, city, country, zip, complete FROM orders
`

func (q *Queries) GetAllOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.UserID,
			&i.Code,
			&i.AmbassadorEmail,
			&i.Firstname,
			&i.Lastname,
			&i.Email,
			&i.Address,
			&i.City,
			&i.Country,
			&i.Zip,
			&i.Complete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
